site_name: RENware Products & Services Catalog
site_author: 'Petre Iordanescu, RENware Software Systems, petre.iordanescu@gmail.com'
copyright: 'Copyright (c) RENware Software Systems'




nav:
    - Home: 'index.md' # here is the system init as being default html to be executed
    - Products catalog: 'wip_page.md' #TODO make a lead page for this catalog section
    - Solutions catalog: 'wip_page.md' #TODO make a lead page for this catalog section #NOTE here to ralk about complex, combined, platforms, ...
    - Services catalog: 'http://www.renware.eu/services.html' #TODO_? make a lead page for this catalog section
    - About CATALOG: 'wip_page.md' #TODO make page 'About_CATALOG.md' and change to
    - License: 'LICENSE.md'
    - RENware Software Systems company: 'http://www.renware.eu'
    - Complete Catalog (PDF): 'wip_page.md' #TODO_change_to 'pdfs/print_page.html/print_page.pdf'








markdown_extensions:
    - admonition
    - tables
    - pymdownx.details
    - pymdownx.superfences:
        custom_fences: #NOTE: [petre iordanescu]: is very important to respect syntax ref `-` character at beginning of items (otherwise not right JSON result !)
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
    - footnotes
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - def_list
    - attr_list
    - md_in_html
    - pymdownx.tasklist:
        custom_checkbox: true




#NOTE required to render `mermaid` diagrams
extra_javascript:
  - optionalConfig.js
  - https://unpkg.com/mermaid@9.4.0/dist/mermaid.min.js
  - extra-loader.js



plugins:
    - search
    - include-markdown
    - markdown-exec #NOTE Python execution inside markdown files (execution at build time, "compilation like" NOT dynamically NOT JavaScript)
    - git-revision-date-localized
    # - pdf-export #NOTE DO NOT USE this as does not render mermaid in PDF docs
    - print-site: #NOTE_IMPORTANT_#NOTE put `print-site` plug in BEFORE `pdf-with-js` in order to works the workaround wit a fake `print_page.md` that will determine generation of 'print_page.pdf' as any other page generated pdf by `pdf-with-js`; ingnore warning ` [mkdocs-print-site] 'print-site' should be defined as the *last* plugin,to ensure...`
        add_to_navigation: true
        print_page_title: 'Complete Catalog'
        add_full_urls: true
        add_table_of_contents: true
    - pdf-with-js:
        enable: true
        #NOTE - all next are examples...
        #author: #NOTE defaulted from site_author item
        #copyright: #NOTE defaulted from copyright item
        #cover: false
        #back_cover: true
        #cover_title: TITLE TEXT
        #cover_subtitle: SUBTITLE TEXT
        #custom_template_path: TEMPLATES PATH
        #
        #toc_title: TOC TITLE TEXT
        #heading_shift: false
        #toc_level: 3
        #ordered_chapter_level: 2
        #excludes_children:
        #    - 'release-notes/:upgrading'
        #    - 'release-notes/:changelog'
        #
        #exclude_pages:
        #    - 'bugs/'
        #    - 'appendix/contribute/'
        #convert_iframe:
        #    - src: IFRAME SRC
        #      img: POSTER IMAGE URL
        #      text: ALTERNATE TEXT
        #    - src: ...
        #two_columns_level: 3
        #
        #render_js: true
        #headless_chrome_path: headless-chromium
        #
        #output_path: any-place/document.pdf
        #enabled_if_env: ENABLE_PDF_EXPORT
        #
        #debug_html: true
        #show_anchors: true
        #verbose: true




#NOTE provide material theme
theme:
    #logo: pictures/SDEVEN_logo.png #NOTE_REN_picture pictures/REN_stamp_logo_transparent.png #FIXME uodate me
    name: material
    features:
        # - navigation.tabs # left navigation side bar, all level 1 will be shown as top navigation bar
        - navigation.tracking
        - navigation.tabs.sticky
        - navigation.path
    palette:
        primary: pink # see https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/ for other color options
        accent: blue
    icon:
        admonition:
            note: fontawesome/solid/note-sticky
            abstract: fontawesome/solid/book
            info: fontawesome/solid/circle-info
            tip: fontawesome/solid/bullhorn
            success: fontawesome/solid/check
            question: fontawesome/solid/circle-question
            warning: fontawesome/solid/triangle-exclamation
            failure: fontawesome/solid/bomb
            danger: fontawesome/solid/skull
            bug: fontawesome/solid/robot
            example: fontawesome/solid/flask
            quote: fontawesome/solid/quote-left



#NOTE or can use readthedocs theme but should check mermaid diagrams
# theme: readthedocs



#NOTE directory where start to search or markdown sources
docs_dir: './doc_src'


#NOTE root directory where to be generated portal (should be `./static_portal`)
site_dir: './static_portal'



#NOTE other useful configurations
use_directory_urls: false # allow link between pages to work properly when used as OFFLINE deployment (ie, static site an "callable" as `file:///...`)


